FROM apache/airflow:2.7.1

USER root

# Install OpenJDK for Spark
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openjdk-17-jre-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Install Python dependencies
COPY ../requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Set Python path
ENV PYTHONPATH=/opt/airflow

WORKDIR /opt/airflow
